### ISSUE TITLE
Missing Windows server startup script

### ISSUE THREAD

**Issue by LlewVallis** [LlewVallis/OpenMissileWars#12]
The `start.sh` script in the `server/` directory should be ported to a language such as Batch or Powerscript so windows users can easily run the prebuilt server archives.

**Comment by Innf107** [comment]
Windows does not support git symlinks, so this script should probably also copy these files over.

**Comment by LlewVallis** [comment]
Luckily my CI pipeline which generates the prebuilt server archives in releases should already resolve all symlinks.

**Comment by LlewVallis** [comment]
I'm thinking this could be solved by creating a "launcher" JAR which could either be run from the command line or double clicked to open. This could replace the current starting script, solving the cross platform issues, and could also handle updating to newer versions of OpenMissileWars for the user.

**Comment by LlewVallis** [comment]
Fixed by the new launcher system in the development branch at 3907af243cc070b9501e3c3deea36630b52f55de
