### ISSUE TITLE
Prevent superflat generation far out in arenas

### ISSUE THREAD

**Issue by LlewVallis** [LlewVallis/OpenMissileWars#19]
There is no void generation in arenas outside of the template's range as was originally intended.

**Comment by Simetraa** [comment]
Took a stab at this today to no avail. While you can still customise world generation options in server.properties, it doesn't seem to work with WorldCreator (always produces default flat world). Seems to be due to this issue https://hub.spigotmc.org/jira/browse/SPIGOT-6237.

**Comment by LlewVallis** [comment]
Huh interesting. Originally there was a mechanism to prevent superflat generation but it mustve broken in a version upgrade

**Comment by LlewVallis** [comment]
Fixed for arenas 859bc33 and then fixed for the hub world in c723916
