### ISSUE TITLE
Add rogue barrier block to map

### ISSUE THREAD

**Issue by LlewVallis** [LlewVallis/OpenMissileWars#20]
The CubeKrowd map contains a single floating barrier block near y=0. This should be replicated in OpenMissileWars.

**Comment by Simetraa** [comment]
Do you know what coordinates the barrier is at?

**Comment by LlewVallis** [comment]
@Simetraa I've heard its around 0 0 32 or 32 0 0 on the CubeKrowd map, but this would need to be verified. If I recall correctly the OpenMissileWars coordinate system is offset from the CubeKrowd one, so that would need to be handled aswell.

**Comment by Simetraa** [comment]
Okay found it. It's at (0, 0, 32). Will look into placing it correctly in the template region files.
![2020-12-15_22 00 39](https://user-images.githubusercontent.com/67224309/102278243-58219a80-3f21-11eb-9cba-942494309175.png)

**Comment by LlewVallis** [comment]
Awesome!

**Comment by LlewVallis** [comment]
Fixed in #27
